server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: jms-template, jms-listener
  jms:
    template:
      default-destination: tacocloud.order.queue
      receive-timeout: 2
  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    embedded:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: rabbitmq-template, rabbitmq-listener
  rabbitmq:
    template:
      receive-timeout: 30000

---
spring:
  config:
    activate:
      on-profile: kafka-listener

  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic