spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api

---
spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: root
    password: Fnst*1234
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tacocloud.order.queue

  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    embedded:
      enabled: false

---
spring:
  datasource:
    username: sa
    password: yourStrong(!)Password
    url: jdbc:sqlserver://localhost:1433;databaseName=tacocloud;
  config:
    activate:
      on-profile: qa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api
