logging:
  level:
    tacos: debug

spring:
  config:
    activate:
      on-profile: dev

  data:
    rest:
      base-path: /api
---
spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud3
    username: root
    password: root
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    tacos: warn

---
spring:
  datasource:
    username: sa
    password: yourStrong(!)Password
    url: jdbc:sqlserver://localhost:1433;databaseName=tacocloud;
  config:
    activate:
      on-profile: qa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    tacos: warn
